# Generated by Django 4.1 on 2024-10-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={'verbose_name_plural': 'musicians'},
        ),
        migrations.AlterField(
            model_name='musician',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
