# Generated by Django 4.1 on 2024-10-25 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0002_alter_musician_options_alter_musician_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musician',
            options={},
        ),
    ]
